# Generated by Django 4.0.3 on 2022-04-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=180),
        ),
    ]
